# Step 1: Build the application
FROM node:21.7.1 AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm install -g npm@10.9.0
RUN npm i
RUN npm run build

# Step 2: Set up the production environment
FROM nginx:stable-alpine

RUN apk add vim bash
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY scripts/pushEnvVars.sh /usr/sbin
RUN chmod +x /usr/sbin/pushEnvVars.sh

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]