# Step 1: Build the application
FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Build the static export
COPY . .
RUN npm run build

# Step 2: Serve the static site with nginx
FROM nginx:stable-alpine

RUN apk add --no-cache vim bash
COPY --from=builder /app/out /usr/share/nginx/html
COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
#COPY scripts/pushEnvVars.sh /usr/sbin
#RUN chmod +x /usr/sbin/pushEnvVars.sh

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]