apiVersion: v1
kind: Service
metadata:
  name: next-js
  namespace: {{ .Values.environment }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: next-js
  sessionAffinity: None
  type: NodePort